### ISSUE TITLE
Feature: Receiving/storing votes as points rather than percentages

### ISSUE THREAD

**Issue by subject026** [BreadchainCoop/breadchain#29]
We're allowing users to define the split they want with point values for each project eg:

Project A - 1 points -> 25%
Project B - 2 points -> 50%
Project C - 1 points -> 25%

Currently we're requiring votes to be submitted as percentages meaning these points need be converted to % on the front-end before sending the tx.
 
We want to allow users to change/update their vote anytime before the next disbursement so we'd need to convert the % back into points on the front-end. This wouldn't actually be possible in some cases because of the rounding that would need to happen to convert certain combinations of points to %.

The best approach IMO would be to just store the user's vote as points and convert them in the contract when necessary.

Because of the rounding that will need to happen we can look at using using permyriad (/10000) rather than percent so we can allocate the remainder without having as much of an impact on the amounts paid out.

We could consider distributing based just on the rounded values and leave the small amount of bread left over from the remainders in the pot for the next disbursement.

**Comment by subject026** [comment]
@RonTuretzky I know we discussed this a bit last week but I'm not sure whether what you have in mind would solve the problem when someone wants to change their vote.

**Comment by RonTuretzky** [comment]
I think maybe we should allow the users to just use their actual voting points, this would simplify things a lot.

**Comment by RonTuretzky** [comment]
@subject026 Begining to implement this
