### ISSUE TITLE
Feature: Documentation and styling

### ISSUE THREAD

**Issue by RonTuretzky** [BreadchainCoop/breadchain#37]
- [x] Natspec 
- [x] Reorganizing 
- [x] Comments 
- [x] Issues from PR #49  [here](https://github.com/BreadchainCoop/breadchain/pull/49#discussion_r1605800999), [here](https://github.com/BreadchainCoop/breadchain/pull/49#discussion_r1605800762) , [here](https://github.com/BreadchainCoop/breadchain/pull/49#discussion_r1605800999) and [here](https://github.com/BreadchainCoop/breadchain/pull/49#discussion_r1605797951)

**Comment by RonTuretzky** [comment]
@bagelface I believe all issues from #49  regarding documentation and styling were addressed in #50 ?

**Comment by bagelface** [comment]
> @bagelface I believe all issues from #49 regarding documentation and styling were addressed in #50 ?

yes i think so. definitely sufficiently to close this issue
