### ISSUE TITLE
OZ signature checker

### ISSUE THREAD

**Issue by RonTuretzky** [BreadchainCoop/breadchain#5]
as @bagelface wrote 
> might consider using [OZ SignatureChecker](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.9.5/contracts/utils/cryptography/SignatureChecker.sol) since it supports [ERC-1271](https://eips.ethereum.org/EIPS/eip-1271) smart contract signatures which could be very important considering the very likely possibility that some votes will be cast via multisig contracts.

https://docs.openzeppelin.com/contracts/5.x/api/utils#SignatureChecker

- [ ] Implement signature checker standard 
- [ ] Create tests for signature passing

**Comment by bagelface** [comment]
There is currently a minor vulnerability with the signature checker in that it only requires percentages in the signature. This means that the same signature can be replayed multiple times, so a users percentages can be reset using any valid signature. To prevent this, the signature should encode a timestamp after which the signature is no longer valid OR use a nonce.

**Comment by RonTuretzky** [comment]
> There is currently a minor vulnerability with the signature checker in that it only requires percentages in the signature. This means that the same signature can be replayed multiple times, so a users percentages can be reset using any valid signature. To prevent this, the signature should encode a timestamp after which the signature is no longer valid OR use a nonce.

Removed this feature on the dev branch
