### ISSUE TITLE
Bug: Fix vote recast expanding voter array

### ISSUE THREAD

**Issue by RonTuretzky** [BreadchainCoop/breadchain#7]
Great catch by @bagelface , voting multiple times with current implementation in [7a0e1ae](https://github.com/BreadchainCoop/breadchain/pull/1/commits/7a0e1ae171db1e30586c07d5109dc533430a9c69) will allow manipulation by casting multiple votes bloating the voters array 

- [ ] Create tests to cover this vulnerability 
- [x] Amend castVote function to account for vulnerability

**Comment by bagelface** [comment]
Will leave this open because we discussed a refactor of this logic, but the bug itself has been fixed.

**Comment by RonTuretzky** [comment]
Closing this, there will be major refactors to the voting logic.
