### ISSUE TITLE
Derive cycle length from actual blocks of distribution 

### ISSUE THREAD

**Issue by RonTuretzky** [BreadchainCoop/breadchain#82]
As explained [here](https://github.com/BreadchainCoop/breadchain/pull/65/files/a42230e432ab989eeeff47883b10c9037dd9c86b#r1676297379) 

- [x] When a distribution occurs, the distribution interval should be updated to be the current block and the last distribution block 
- [x] Voting power should be reconfigured to be calculated from the last actual interval between distributions

**Comment by bagelface** [comment]
https://github.com/BreadchainCoop/breadchain/pull/102
