### ISSUE TITLE
Error definition location convention

### ISSUE THREAD

**Issue by RonTuretzky** [BreadchainCoop/breadchain#85]
As brought up in #78 [here](https://github.com/BreadchainCoop/breadchain/pull/78#discussion_r1733808094) there are arguments for and against the location of errors (interface vs implementation), a repository wide convention must be decided and refactors executed to enforce the convention.

**Comment by bagelface** [comment]
will likely be resolved with https://github.com/BreadchainCoop/breadchain/issues/89
