### ISSUE TITLE
Create smart contract "style guide"

### ISSUE THREAD

**Issue by bagelface** [BreadchainCoop/breadchain#89]
Create a "style guide" for smart contract development that sets clear expectations for style, formatting, and organization of code submitted to this codebase. The guidelines should be consistent with industry standards.

**Comment by bagelface** [comment]
Will likely just be creating a reference to this style guide and updating the contracts to be consistent with it: https://github.com/bcnmy/biconomy-solidity-style-guide

It's detailed without being super heavy handed and covers everything we wanted to cover with our style guide and more.

**Comment by rubydusa** [comment]
I'm working on an issue and I just wanted to know if there's some extension or plugin or automatic way to format?

**Comment by bagelface** [comment]
> I'm working on an issue and I just wanted to know if there's some extension or plugin or automatic way to format?

You can use the [foundry formatter](https://book.getfoundry.sh/reference/config/formatter) and/or [solhint](https://github.com/protofire/solhint) but since this is a custom style guide, not everything will be enforced.

**Comment by bagelface** [comment]
Completed with https://github.com/BreadchainCoop/breadchain/pull/93
